### PR TITLE
Fix slider truncation

### PR DESCRIPTION
**Pull request by dnicolson**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dnicolson** [comment]
Hi @avallete, can you please take a look at this?

**Comment by avallete** [comment]
@dnicolson thanks for contributing ! Could you detail a bit more what's the bug, on which browser it's happening and how your change fix it ? I have trouble to figure out the context of it.

Screenshots could be nice as well if it's a UI issue.

**Comment by dnicolson** [comment]
Before:


After:

**Comment by avallete** [comment]
> Before:
> 
> 
> After:
> 
> 

Thanks for providing details. LGTM !

**Pull request merged**
