### PR TITLE
Fix grammar in button description

### PR DESCRIPTION
**Pull request by dnicolson**
This pull request fixes the grammar of the text that appears above the remove button.

### CODE REVIEW

**Comment by avallete** [comment]
Nice one

**Review by avallete — CHANGES_REQUESTED** [review]
The project now uses automatic semantic release based on commit messages. I added pre-commit and pre-push validation so you should have a message locally telling you that the commit message doesn't fit the commit convention.

Please could you reword your commit message based on [conventional commit covention](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) ? Something like: `fix(typo): grammar in button description`

**Comment by avallete** [comment]
Nice one, just a minor fix in commit message and we should be ready to merge

**Comment by dnicolson** [comment]
I've changed the commit message.

Speaking of the build process, do you think bundle minification is needed? The script doesn't go over the wire on every request so there isn't a performance advantage. If minification was removed it would be possible again to edit the userscript in the browser.

**Comment by avallete** [comment]
> I've changed the commit message.
> 
> Speaking of the build process, do you think bundle minification is needed? The script doesn't go over the wire on every request so there isn't a performance advantage. If minification was removed it would be possible again to edit the userscript in the browser.

Yep, that was a question I asked myself as well. But, since the package now use webpack to transpile from Typescript to Javascript the "userscript" isn't really easily readable anyway (full of webpack bundling logic). However, maybe adding some extra documentation on how to clone and setup dev environment to contribute/tweak the script could be nice.

**Review by avallete — APPROVED** [review]

**Pull request merged**
