### PR TITLE
Add mark as unwatched button

### PR DESCRIPTION
**Pull request by dnicolson**
## Description

Briefly playing a video can often result in the whole video being marked as watched. Adding this button is a convenient way to prevent actual unwatched videos from being removed when removing all watched videos.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Closing issues

Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by dnicolson** [comment]
Hi @avallete, can you please take a look at this?

**Comment by avallete** [comment]
Yeah I think that's an issue with youtube itself. It usually happen if you start a video, then go toward the end without watching anything. Note that the opposite can also happen if you got to the beginning of an already watched video.

Anyways, this change LGTM, but could you provide some screenshot of what it'll look like in the UI ?

**Comment by dnicolson** [comment]
PixelSnap 2024-05-06 at 18 57 55@2x
PixelSnap 2024-05-06 at 18 58 07@2x

**Comment by avallete** [comment]
> PixelSnap 2024-05-06 at 18 57 55@2x
> PixelSnap 2024-05-06 at 18 58 07@2x
> 

Thanks for contributing !

**Pull request merged**
